Syzygy
======

Configuration system aiming to replace cetera and api-properties.

This is work in progress, and some of it needs research / testing.


Epic: http://apidev.atlassian.net/browse/DEVOPS-346

Currently, much of the main code reside in pantheon. This will be moved RSN.

etcd documentation
------------------

* https://github.com/coreos/etcd
* https://github.com/coreos/etcd/blob/master/Documentation/api.md

Syncronization
--------------

Command line after building project::

  java -Dlogback.configurationFile=syzygy-service/src/test/resources/logback.xml \
       -jar syzygy-service/target/syzygy-service-0.0.2-SNAPSHOT.jar \
       syzygy-etcd/src/test/resources/structure.yml http://127.0.0.1:4001/v2/ \
       structure
