// -*- Doc -*-

Syzygy
======
:toc:
:icons: font
:source-highlighter: prettify

Syzygy is a Java based *configuration system* vaguely
inspired by
https://docs.puppetlabs.com/hiera/1/index.html[Hiera]
and
https://github.com/mozilla/node-convict[convict.js].

You store the configation in `JSON`, `yaml` or in
https://github.com/coreos/etcd[etcd]. Or in a
self baked legacy way, with a
https://github.com/amedia/syzygy/blob/master/syzygy-core/src/main/java/no/api/syzygy/SyzygyDynamicLoader.java[minimal
implementation].

The heart of these systems is support for overriding a "common" or
"default" setting.

## Configuration file

The normal way of configurating syzygy, is to create a configuration file,
typically named `syzygy.yaml`:

[source,yaml]
---
:datadir:
  - hieradata
:hierarchy:
  - special    # Finest granularity
  - role       # A specific
  - no.api.someapp.SomeImplementation
  - common     # Fallback level
stop_if_error: true

This says you store your data in the directory named `hieradata`.
Otherwise, the files are assumed to
be stored in same directory as the configuration file. Note that the hieradata
directory is *relative to the  syzygy.yaml* file -- which means that if you fetch it
over HTTP, the address will be relative to that HTTP address.

The content of the files can have 3 different formats:

. yaml - support for nesting levels, hierarchical data, lists and maps.
. json - plain json, support nesting levels
. json (as convict.js format). Supports data types *, int and url and will
   validate all data.

Basically, everything that is supported by
https://github.com/FasterXML/jackson[Jackson]
is supported by syzygy.

You may refer to a java implementation, as in the `SomeImplementation`
example. More about the correct format for this later.

### Etcd configuration

By adding the configuration class `EtcdConfigurationProvider`, you can
configure an etcd entry point. The following is an example with etcd connection
added.

[source,yaml]
---
:datadir:
  - hieradata
:hierarchy:
  - no.api.syzygy.etcd.EtcdDynamicConfiguration#inetcd
  - infile
stop_if_error: true
global_etcd_url : "http://127.0.0.1:4001/v2/"
inetcd_etcd_prefix : "/syzygy/somewhere/"

The configuration `inetcd` can be found in etcd, and `infile` in the directory
`hieradata`. Notice that `EtcdDynamicConfiguration` need configuration of
where to find etcd, namely `global_etcd_url`

Note the configuration which is specific for etcd:

* TAG_etcd_url: Where to connect to etcd. Defaulting to localhost
* TAG_inetcd_etcd_prefix: The prefix within etcd. Defaults to `syzygy`. The
  configuration from hierarchy would be added to the path, so in the
  example, the hierarchy starts with `/syzygy/somewhere/inetcd/


### yaml configuration example

Yaml is the format you would know already from dropwizard configuration:

[source,yaml]
key1: 'value from common'
map1:
  - key1: 'array key1'

### Plain JSON

[source,json]
{
  "key3": "Key3 from json",
  "map1": {
    "internal_1": "somevalue_1"
  }
}

### Convict file format

Json in convict style:

[source,json]
{
    "example": {
        "doc": "Example doc.",
        "format": "*",
        "default": "default_value"
    }
}

Doc entries can also be written in yaml:

[source,yaml]
example:
  doc: 'Example doc.'
  format: '*'
  default: 'default_value'
      

The key name is `example`, and it is in "any" format. The "default"
value is what this configuration will return if it is not overridden.
The configuration will be used if validate is called.

*Note* that convict configuration is *only supported in JSON and yaml* files,
and *not* in etcd and dynamic configurations.


### Programmatic no.api.someapp.SomeImplementation

Implement `SyzygyDynamicLoader`. This gives you access to the top
level Syzygy where you can add configuration which your class might need
for bootstrapping.

Example:

[source,yaml]
---
:hierarchy:
  - special
  - no.api.syzygy.DirectoryIntoMap#refkey
  - fallback
refkey_directory_to_map: overrides
stop_if_error: 'true'

Explanation: The class `DirectoryIntoMap` will load all files from
the configuration `_directory_to_map`. The "special" configuration will
override all configuration. The `DirectoryIntoMap` values will override
the "fallback" values. See: +
 https://github.com/amedia/syzygy/blob/master/syzygy-core/src/main/java/no/api/syzygy/loaders/DirectoryIntoMap.java

## Query through the SyzygyLoader

The interface has some entry points which can be used to
find configured values:

* `static SyzygyLoader loadConfigurationFile( File config )` : How you instantiate Syzygy (presently)
* `String lookup(String key)` : Regular query for string value
* `<T> T lookup(String key, Class<T> clazz)` : Lookup for key with a special class - typically a map
* `List<SyzygyPayload> listAllProperties()` :
https://github.com/amedia/syzygy/blob/master/syzygy-core/src/main/java/no/api/syzygy/loaders/SyzygyLoader.java
* `String deepLookup(String key, String nameOfMap)` : For each configuration file, first try
  lookup in map. This is functionally similar to ApiPropertes#lookup(key, publication );
* `<T> SyzygyPayload<T> lookupFor(String key, Class<T> clazz)` : Lookup value and get the
  syzygy payload object which contains more information, most interestingly, the documentation.
* `void flush()` : Reload config (but currently not parent config)
* `void validate` : Validate all elements against convict definition.
* `Set<String> keys()` : The composite collection of keys

### Listing used variables

By combining the listAllProperties, can you find all properties, and whether they are used.
Example of output from
https://github.com/amedia/syzygy/blob/master/syzygy-core/src/test/java/no/api/syzygy/loaders/SyzygyLoaderTest.java#133


   convict     1            key4                                         key4_value
   convict     1 shall_be_intege                                                123
      key3     1            key3                                     Key3 from json
      key3     2            key4                                     Key4 from json
      key3     1         jsonmap   {internal_1=somevalue_1, internal_2=somevalue_2}
  specific     1            key1                                      from specific
  specific     1          array2                 [{key2=overridden array, one key}]
    common     2            key1                                  value from common
    common     1            key2                                  value from common
    common     2            key3                                  value from common
    common     1          array1             [{key1=array key1}, {key2=array key2}]

## Amedia specific doc

image::https://avatars0.githubusercontent.com/u/582844?v=3&s=200[Amedia Logo]

Please see internal documentation at:
https://github.com/amedia/syzygy-dw
