// -*- adoc -*-

# Syzygy and gaia configuration in Amedia

:toc:
:icons: font
:source-highlighter: prettify

Gaia tries to read values from syzygy *first*, and then it tries to read from
apiproperties *next*. This implies that if you have *not* started to use syzygy,
the configuration setup is _exactly as before_, i.e. `wp` and friends.
You are *recommended to add new and updated configuration to syzygy*
and *only* to syzygy -- if practically feasible, of course.

As explained in
link:migration[the migration document], the natural choice for REST interface
is Gaia.

## Linpro configuration of syzygy

The main configuration resides within ikea in the file
`ikea/etcapi/syzygy/syzygy.yaml.template`

A copy of the (current) content is as follows, with explanation underneath:

----
:datadir:
  - config
:hierarchy:
  - ../override
  - no.api.syzygy.etcd.EtcdDynamicConfiguration#<%= scope.function_hiera('c_api::backend_type') %>
  - no.api.syzygy.etcd.EtcdDynamicConfiguration#primary
  - no.api.syzygy.loaders.DirectoryIntoMap#publication_override
  - common
global_etcd_url : "http://<%= scope.function_hiera(['etcd_host']) %>:<%= scope.function_hiera(['etcd_port']) %><%= scope.function_hiera(['etcd_path']) %>"
primary_etcd_prefix : "/syzygy/"
stop_if_error: false
publication_override_directory_to_map: publication
----

The lookup is performed in the following *sequence*:

. override as defined in puppet file `ikea/etcapi/syzygy/override.yaml.template`
. `role_domain` in etcd, which is `/syzygy/snapshot, /syzygy/test, /syzygy/prod`
. the etcd variables for all domains: /syzygy/primary
. the files in the publication directory. They can be used for overriding specific publication variables
. the file config/common.yaml

The meta configuration is

|===
| global_etcd_url | Where to find the etcd URL
| primary_etcd_prefix | In etcd, which path is the start path for syzygy. This is needed as we share etcd with linpro.
| stop_if_error | The exact behavior of this is work in progress:
                   https://apidev.atlassian.net/browse/DEVOPS-505. It means that syzygy won't throw exception during
                   startup even if a configuration is wrong / faulty / fishy.
| publication_override_directory_to_map | the directory `publication` is parameter to the `DirectoryIntoMap` class.
|===


### Comparison with wp.xml

In order to make syzygy easier to understand, this is a comparison with the wp system:

|===
| variable in syzygy.yaml | syygy | wp

| override.yaml.template | File in svn with values populated by puppet, `ikea/etcapi/syzygy/override.yaml.template` | `ikea/etcapi/wp/wp-override.xml.template`
| `EtcdDynamicConfiguration`#prod | Key in etcd under `syzygy/prod/key`  | Wp does not have etcd support
| `EtcdDynamicConfiguration`#primary | Key in etcd under `syzygy/prod/primary` - etcd fallback  | N/A
| `DirectoryIntoMap`#publication_override | Files in `cetera/syzygy/publication` such as `www.rb.no.yaml` | `cetera/wp/www.rb.no/wp.xml`
| common.yaml | `cetera/config/common.yaml` | `cetera/wp/wp.xml`
|===

