// -*- Doc -*-

## Implementation notes and comments

:toc:
:icons: font
:source-highlighter: prettify

### Syzygy configuration file

The configuration file lists up the depending files in the sequence of checking.

Example file:

  :datadir:
    optional_data_directory
  :hierarchy:
    - first_file
    - second_file
    - third_file

If `:datadir:` is not given, the directory of the configuration file
is assumed.

The files are searched for the value in ascending other, and the first
value is chosen. So the last file would be "common", and the first
file the specific file.

### TODO

* The convict script and definitions are only active in the
  actual convict instance. Create an implicit meta format. (Is still still true??)

* Support for getting configuration from java classes. *Answer*: Dynamic loader

* %{dynamic} variables. *Answer*: Implement more dynamic loaders if necessary

* List of available variables. *Answer*: Done

* Need validation
** Not legal with same key several times in same file: *Answer*: Jackson says whats legal or not
** Wrong type in convict def, also when using sub config. Answer: Validate will check against all convict schemas

* Need to decide what to do when having config error. Throw exception, or log?
  *Answer*: Configurable
