// -*- Doc -*-

# Migration from api-properties

:toc:
:icons: font
:source-highlighter: prettify

The situation as of 20/4--2015, is that the ApiProperties object, and interfaces
have been moved to `pantheon-core`. The Publication related material has been
moved to `pantheon-publication`. This helps you to move away from the api-properties
as a library.

Quick summary of your choices:

[cols="2*"]
|===
|gaia-client             | A REST based client setup, which is what all the dropwizard applications currently use
|gaia-apiproperties      | A drop-in replacement for api-properties, which communicates over gaia-client
|syzygy                  | Next-generation configuration system. Use it directly, if you do not want other gaia features.
|syzygy-apiproperties    | Drop-in replacement for api-properties, which use syzygy only as backend
|===

In more, detail, your choices are:

## gaia-client

Gaia-client reads first from syzgyy, and then from api-properties in order to provide
a value over the REST interface. The default choice, but it does not help you migrate
away from `wp.xml` / `wp-override.xml`

When you are working on your local dev setup, the annoyance is that you need
ẗo have gaia running in order to get access to the values.

Additionally, it can be a bit hard to know where a value actually comes from.

## gaia-apiproperties

Replacing `api-properties` with gaia. You need to change some wiring in your spring
configuration.

First step is to remote the old api-properties setup in the main pom file, *and* the child poms:

[source,xml]
-----
<dependency>
    <groupId>no.api</groupId>
    <artifactId>properties</artifactId>
    <version>${apiproperties.version}</version>
</dependency>
-----

Add:

[source,xml]
-----
<dependency>
    <groupId>no.api.gaia</groupId>
    <artifactId>gaia-apiproperties</artifactId>
    <version>${gaia.version}</version>
</dependency>
-----

Then the fun begins. You have to prune away all old references to api-properties.
Do:

[source,bash]
mvn dependency:tree | grep "api:properties"

For each entry you find, you need to exclude the api-properties element:

[source,xml]
-----
<dependency>
    <groupId>no.api.relax</groupId>
    <artifactId>relax-director-provider</artifactId>
    <version>${relax.version}</version>
    <exclusions>
        <exclusion>
            <groupId>no.api</groupId>
            <artifactId>properties</artifactId>
        </exclusion>
    </exclusions>
</dependency>
-----

Rinse and repeat, until all references to api-properties has been removed.

Find the *wp.xml* file, and change the spring configuration for api-properties
to `classpath:/META-INF/gaia-apiproperties.xml`.

Add JNDI configuration to jetty.xml, so you are able to do `mvn jetty:run`

[source,xml]
-----
<New class="org.eclipse.jetty.plus.jndi.EnvEntry">
    <Arg>gaiaUrl</Arg>
    <Arg type="java.lang.String">http://localhost:9050/gaia</Arg>
</New>
-----

You need to have jetty-plus and jetty-annotation support in your webapp for JNDI to
work. In your -app project, you need to add the JNDI configuration to the
api-properties.xml file. This necessitates the jetty-plus configuration, and
annotations (for unclear reasons).

Finally, when deploying, you need to have the JNDI element in ikea too. See example
from kraken to see how this is configured. (This is better than to describe it here,
in case this description becomes stale.)

## syzygy

The next generation configuration system. Currently, mainly relevant when it provides an
interface to etcd.

## syzygy-apiproperties

Configuration without gaia. Drop-in configuration of xml files.
